name: Build and Push Dev Image
# Workflow name

on:
  push:
    branches:
      - dev
# Trigger the workflow on a push to the 'dev' branch

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    # Runner OS
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
        # Checkout the code from the repository
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        # Log in to Docker Hub using credentials stored in secrets

      - name: Build Image
        run: docker image build -t ing2isimm2024/simplewebdev -f Dockerfile.dev .
        # Build the Docker image using Dockerfile.dev
        
      - name: Push Image
        run: docker image push ing2isimm2024/simplewebdev
        # Push the Docker image to the registry
