name: Shell Commands
# Workflow name

on:
  push:
    branches:
      - dev
# Trigger the workflow on a push to the dev branch

jobs:
  run-shell-command:
    # Job name
    runs-on: ubuntu-latest
    # Runner OS

    steps:
      # Array of steps
      - name: Echo a string
        run: echo "Starting"

      - name: Run multiline script
        run: |
          node -v
          npm -v
